### ISSUE TITLE
Organize request and response models vs. internal models 

### ISSUE THREAD

**Issue by callebtc** [cashubtc/cashu-ts#109]
`src/model/types/index.ts` hold all models – for the API And for internal representations without any particular ordering. Models should ideally be sorted together into these two categories or be even defined in separate files.

**Comment by andrew-weber** [comment]
I think think this issue is very important. I am still learning my way through this repo, but so far I've spent a lot of time creating a mental map of the different models with nearly identical names. 

As an example 

This is from the Readme.md
```
async function invoiceHasBeenPaid() {
	const { proofs } = await wallet.requestTokens(200, hash);
	//Encoded proofs can be spent at the mint
	const encoded = getEncodedToken({
		token: [{ mint: '{MINT_URL}', proofs }]
	});
	console.log(encoded);
}
```

Here's the source for `getEncodedToken`
```
function getEncodedToken(token: Token): string {
	return TOKEN_PREFIX + TOKEN_VERSION + encodeJsonToBase64(token);
}
```

Here's the model `Token` definition:
```
export type Token = {
	/**
	 * token entries
	 */
	token: Array<TokenEntry>;
	/**
	 * a message to send along with the token
	 */
	memo?: string;
};
```

and heres the `TokenEntry` definition:
```
**export type TokenEntry = {
	/**
	 * a list of proofs
	 */
	proofs: Array<Proof>;
	/**
	 * the mints URL
	 */
	mint: string;
};**
```


Somewhere in here, I think we'd benefit from drawing differences between `<Token>` & `<TokenEntry>`.  Also I think it's confusing to stay `<Token>`'s only required field is `token: Array<TokenEntry>`, are they tokens or tokenEntries?.

**Comment by cjbeery24** [comment]
@callebtc Pull request here.
https://github.com/cashubtc/cashu-ts/pull/153

**Comment by Egge21M** [comment]
@callebtc this can be closed, right?
