### ISSUE TITLE
NUTs - Implement changes to NUT-04/NUT-05 method settings struct

### ISSUE THREAD

**Issue by callebtc** [cashubtc/cashu-ts#114]
Implement changes in https://github.com/cashubtc/nuts/pull/82 to v1_api branch

**Comment by Dayvvo** [comment]
So far I can see that the `/info` endpoint v1_api branch is already defined to return a response that matches `MintMethodSetting` namely:

```
{
  "method": "bolt11",
  "unit": "sat",
  "min_amount": 0,
  "max_amount": 10000        
}
```

only thing left is that the type should be renamed to  MintMethodSetting instead of SwapMethod. Anyone working on it or can I make a PR to correct that and push?

**Comment by callebtc** [comment]
> Anyone working on it or can I make a PR to correct that and push?

I've done it here: https://github.com/cashubtc/cashu-ts/pull/131

**Comment by Dayvvo** [comment]
Alright. I guess all that's left is to close it out, yeah?
