### ISSUE TITLE
gandlafbtc/cashu-crypto-js

### ISSUE THREAD

**Issue by BilligsterUser** [cashubtc/cashu-ts#20]
Should we include the code from https://github.com/gandlafbtc/cashu-crypto-js in this repo?

**Comment by gandlafbtc** [comment]
You mean the mint related step2 and verify code? I think we could. It doesn't hurt to have it in the lib. I was a bit reluctant on doing that, somehow i wanted to separate mint and wallet logic to avoid confusion. 

we could also include cashu-crypto-js as a module, since it implements all the crypto functions, and remove the crypto stuff from cashu-ts. This would probably be the cleaneest, but would need a little bit of refactoring.

What do you think? @BilligsterUser

**Comment by BilligsterUser** [comment]
Using cashu-crypto-js as a module can simplify the code . 
Having all crypto functions in one module can be a good idea .

**Comment by callebtc** [comment]
Please add it to cashu-ts, so people can use it to build mints!
